### PR TITLE
Agr 305 orthologs revision 1

### PR DESCRIPTION
**Pull request by sibyl229**
- fix ortholog score denominator
- sort orthologs by species taxonomic order, and when tie sort by score numerator
- indicate species alteration by table row shading

for testing:
http://dev.alliancegenome.org:4001/gene/WB:WBGene00000912

AGR-305

### CODE REVIEW

**Comment by paaatrick** [comment]
Oops, I just noticed a small bug after I hit the approve button 😁 

If the ortholog list goes directly from mouse to fish (i.e. doesn't include rat), the shading doesn't work. For example: http://dev.alliancegenome.org:4001/gene/RGD:61995

Also, maybe I was misunderstanding what the styling request was, but I thought they were asking for like a heavier line between different species. Maybe it would be easier to put an extra class on the first row for each species and use that to set a heavier/darker top border?

**Comment by sibyl229** [comment]
Thanks @paaatrick ! Haha I noticed kinda the same problem after I made the PR. I just pushed and re-deployed. How about this one: http://dev.alliancegenome.org:4001/gene/WB:WBGene00000912

**Comment by sibyl229** [comment]
@paaatrick I admit I use shading cuz it seems easier than line, which has to be added to the **first** of ortholog of a species. Couldn't think on top of my head of how to know if an ortholog is a first. So requirement says "11. Use visible marker (e.g. line, or different colours) to separate species".

**Comment by paaatrick** [comment]
works for me!

**Pull request merged**
