### PR TITLE
Initial index of basic gene info

### PR DESCRIPTION
**Pull request by kevinschaper**
- Fields are added to ES schema to match the basic gene information schema
- Load is pulling from Wormbase and ZFIN files basic gene info files, along with Mouse sample
- Fields that are expected by the search code but don't match the basic gene info schema are still being populated.

### CODE REVIEW

**Comment by a8wright** [comment]
@kevinschaper feel free to reach out to me if you need help testing with AWS ES  Services index

**Comment by kevinschaper** [comment]
There's no change here for it connects to ES, it just pulls from the environment variable.  I would say pull #90 in and then I'll set up the AWS permissions to get things indexed, but if the AWS setup we have now fails with an out of memory error for #90, it'll fail for this one too.   It's possible that for 0.3 we might not be able to index on a low memory host?

**Comment by pedrohr** [comment]
Great job everyone!!! I left two comments in the review section. We can merge and continue moving ahead.

And yes, we need at least a medium instance on AWS for indexing or it's going to crash. ES loves RAM. Once the data is indexed, if the cost is a problem we can reduce the instance a little bit.

**Comment by christabone** [comment]
This all sounds great -- in about an hour or so I'll merge #90 followed by #91. If anyone objects, please let me know!

**Pull request merged**
