### PR TITLE
AGR-260 Fixed genomeLocation bug.

### LINKED ISSUE #245: genomeLocations has a null start and end all of the time
@christabone   . . @kevinschaper  suggested you might be the person to ask.

```
"gene_molecular_function": [], 
  "genomeLocations": [
    {
      "assembly": "GRCv10", 
      "chromosome": "13", 
      "end": null, 
      "start": null, 
      "strand": null
    }, 
    {
      "assembly": "GRCv10", 
      "chromosome": "13", 
      "end": null, 
      "start": null, 
      "strand": null
    }, 
```

### PR DESCRIPTION
**Pull request by christabone**
This fixes #245 and removes some older unused chromosome location code from the prototype.

Related JIRA -- http://jira.alliancegenome.org/browse/AGR-260

### CODE REVIEW

**Comment by nathandunn** [comment]
@christabone  I like the idea of getting rid of these if not needed.  I need to retest, though.  If I do a ```make index``` will it blow out the old data or do I need to do something else?

**Comment by christabone** [comment]
Correct, it'll remove the old data, you should be good!

**Comment by nathandunn** [comment]
K.  I'll try to get it tested today.

**Comment by nathandunn** [comment]
@christabone  Looks good.  A lot faster load process as well.

**Comment by christabone** [comment]
Great! Thanks for testing. I'll merge into development.

**Pull request merged**
