### PR TITLE
fixes #183

### LINKED ISSUE #183: RGD entries missing "RGD" prefix
image

An accidental change from the Human Gene Report fix?

### PR DESCRIPTION
**Pull request by sierra-moxon**

### CODE REVIEW

**Comment by oblodgett** [comment]
I don't know if we are going to show these id's this way but I know MGI:MGI:12345 really bugs people here.

**Comment by kevinschaper** [comment]
This fixes the gene page to show RGD:123456, so I'm bringing it in, but the bummer is that it's still linking from search with /gene/123456 rather than /gene/RGD:123456 

So, more to do, but this is still worth bringing in.

**Comment by cmungall** [comment]
+1 to fixing to double MGI error before it becomes too late

**Comment by oblodgett** [comment]
I deleted that comment, after I realized there is a conditional for a specific organism.

**Comment by sierra-moxon** [comment]
We fixed the MGI issue already before this bug - this fix is then to fix the RGD ids that went prefix-less by the fix for MGI.  Some folks have prefixes built into their IDs and some don't.

**Pull request merged**
