### PR TITLE
Fix gene_type in search results (renamed to Biotype)

### LINKED ISSUE #164: Populate gene_type in /search api results
It's coming back empty right now, but should get populated with soTermName from the index

### PR DESCRIPTION
**Pull request by kevinschaper**
Fixes #164

### CODE REVIEW

**Comment by oblodgett** [comment]
Does this need a reindex in dev, stage, prod?

**Comment by christabone** [comment]
Yes, for sure. Along with the disease changes -- it'd be great to reindex.

**Comment by oblodgett** [comment]
Index has been started.

**Comment by oblodgett** [comment]
Index is now finished.

**Pull request merged**
