### PR TITLE
Feature functional tests

### LINKED ISSUE #243: create front to back functional test
Look at using TravisCI to build the index, cache it, and then test it using some kind of nice BDD testing tool and a python wrapper around selenium.

### PR DESCRIPTION
**Pull request by kevinschaper**
Adds indexing into to ES to the travis build, brings in the behave python testing framework as well as selenium webdriver to connect, render the page and confirm that at least a small token bit of data is present. 

This bumps the travis build time to 13 minutes, and obviously as we load more data would go up.  Once the time is unacceptable, we should look at a way to truncate loads so that we're bringing in a subset of the data from each source. 

@christabone I added you as a review since I'm hoping this will be helpful to you as you refactor the load - feel free to remove yourself if you're buried in that refactoring work

Fixes #243

### CODE REVIEW

**Comment by christabone** [comment]
Whoa, cool. I am indeed buried in the load re-writing right now but hopefully I can look over everything later today!

**Comment by sierra-moxon** [comment]
I think it would be interesting to explore Kevin's idea of a flag on the loader that tells it to only pull the first x number of records for the travis build.  That way we don't necessarily have to keep a test data store around and up to date.

**Comment by oblodgett** [comment]
The only issue with that, is it might be all ZFIN genes or MGI genes, and not a complete data selection from across the whole set.

**Comment by kevinschaper** [comment]
My feeling is that this is mostly about the infrastructure for the tests, so nothing here should stop us from whatever subsetting we do to speed things up in a future. 

My thought for subsetting was something like first 100 or 1000 from each BGI file and see how much that speedup we can get, but if we can live with the 13 minute CI time, let's make a new issue for that and maybe work on it after @christabone's load refactoring.

**Comment by christabone** [comment]
The loader has been re-written to load on a per-MOD basis* so @kevinschaper's should be hopefully straightforward to implement.

*_e.g._ Load fly genes in batches of 5000, annotate with GO/SO, load into ES.

**Comment by kevinschaper** [comment]
@sibyl229 I just realized that you tested this for me, so I thought I'd tag you as a potential reviewer too

**Comment by oblodgett** [comment]
Kevin before merging this in can you make the following changes:

server.py:13 change timeout from 5 to 30.
test_search.py:11 remove line: os.environ['ES_HOST'] = 'localhost:9200'
test_search.py:71 change: self.index = 'searchable_index_blue' to self.index = 'os.environ['ES_INDEX']

All the tests pass with these modifications, and it also fixes the "make test-py" in our GoCD server thanks.

**Comment by kevinschaper** [comment]
I made the updates - thanks for testing it against GoCD!

**Comment by christabone** [comment]
We'll have some extremely minor conflicts in the aggregate loader file with my PR following yours. Should be simple to resolve. 

As far as I can tell, this looks good!

**Comment by oblodgett** [comment]
GoCD actually runs all the way through.
All tests pass and the setup does not fail.

**Pull request merged**
