### PR TITLE
Include geneSynopsisUrl in Description field. Fixes #218

### LINKED ISSUE #218: geneSynopsisUrls not being displayed
Gene synopsis text is being displayed, but gene synopsis URLs are not.
Example: 
http://staging.alliancegenome.org/gene/MGI:109337
Should display this URL:
http://staging.alliancegenome.org/gene/MGI:109337

This gene onl;y has a synopsis URL:
http://staging.alliancegenome.org/gene/MGI:98341

### PR DESCRIPTION
**Pull request by paaatrick**

### CODE REVIEW

**Comment by paaatrick** [comment]
This seems to have gotten stuck in CI after merging in changes from the release/0.3.0 branch. So, I'm going to close this PR and open a new one.

**Comment by oblodgett** [comment]
I was asked earlier today to pause the CI to any further changes?

**Comment by paaatrick** [comment]
I was referring to Travis CI, the thing that runs the tests automatically. I think that's separate from whatever was doing automatic deployment?

**Comment by oblodgett** [comment]
Oh ok... yes.

**Pull request closed without merging**
