### PR TITLE
Fixed names and aliases in autocomplete

### LINKED ISSUE #151: Include "Name" and "Synonyms" in search auto-complete

### PR DESCRIPTION
**Pull request by kevinschaper**
Converted autocomplete ES query to use a dismax query so that it will query against multiple fields with different weights
Added a boosting strategy that favors exact symbols and aliases first, followed by (whitespace split) starts-with matching on symbol, aliases and names.
Fixed some bad matching because the starts-with tokenizer was running at both index and query time, returning false positives if they started with the same substring
(plus a little bit of drive-by automated tab to space reformatting)

Fixes #151

### CODE REVIEW

**Comment by christabone** [comment]
Wow, nice work Kevin, this is awesome.

**Comment by christabone** [comment]
Any thoughts on the conflict resolution?

**Comment by kevinschaper** [comment]
Whoops, I'll merge development in and get rid of the conflict

**Comment by kevinschaper** [comment]
Ok, merged and conflict free!

**Comment by christabone** [comment]
Looks good to go IMO. Perhaps lets merge in the morning in case anyone else wants to review it?

**Pull request merged**
