### PR TITLE
AGR-367 ribbon integration

### PR DESCRIPTION
**Pull request by sibyl229**
**For discussion only. Please DON'T Merge**

- use @selewis 's `<Ribbon />` component https://github.com/geneontology/ribbon on gene page
- `<RibbonDataProvider />` is used to retrieve data from the API provided by GO and provide the data to `<Ribbon />`. `RibbonDataProvider` will go away when data is available in our Redux store. For now I think data is best contained in the component, as nothing else in AGR website should on this data and its format until full data ingestion. 

A testing site running off this branch is deployed: [http://dev.alliancegenome.org:4001](http://dev.alliancegenome.org:4001)

Example genes (please feel free to add to the list): 
- MGI:97490

### CODE REVIEW

**Comment by sibyl229** [comment]
Hi @oblodgett a question, is it possible to have this branch served from dev machine port and be part of the the continuous integration? If it's possible, would you like me to submit a Jira issue for that? Thanks!

**Comment by oblodgett** [comment]
Yes... however being on vacation, I can do this first thing Monday.

**Comment by sibyl229** [comment]
@oblodgett Oh great! I will remind you when you get back. Have a nice vacation!

**Comment by sibyl229** [comment]
Hi @oblodgett just to let you know. Don't worry about this issue when you get back. With @a8wright 's help, I could deploy manually to a port on dev instance. I wrote my name on the port claiming document in the architecture WG google drive. Thanks any away.

**Comment by sibyl229** [comment]
Hi @bryon-czoch yes, good reminder. I will work with @selewis to have it published on NPM. This needs to happen before this PR can be merged.

**Pull request merged**
